name: Java CI

on:
  push:
    branches: [ develop, release/* ]
  pull_request:
    branches: [ develop, release/* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK 17 тохируулах
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkstyle шалгах
        run: mvn checkstyle:check

      - name: Тест + JaCoCo + Coverage check
        run: mvn verify
